steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'postgres-appliance'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      ./build.sh \
        -t gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID \
        -t gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME \
        .
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'
